---
# Source: microservice/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ms-microservice
  labels:
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: ms
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm

type: Opaque
stringData:
  API_TOKEN: ""
---
# Source: microservice/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-microservice
  labels:
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: ms
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
data:
    APP_LOG_LEVEL: "info"
---
# Source: microservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ms-microservice
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ms-microservice
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
# Source: microservice/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ms-microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ms-microservice
    spec:
      imagePullSecrets:
      - name: ghcr-pull
      containers:
        - name: app
          image: "ghcr.io/milo1409/microservice:dev"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: "dev"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
