name: ci-dev

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write       
  packages: write       

env:
  IMAGE_REPO: ghcr.io/milo1409/microservice
  VALUES_FILE: helm/microservice/values-dev.yaml

jobs:
  build-push-and-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push (tag short-SHA)
        run: |
          TAG=${{ steps.vars.outputs.SHORT_SHA }}
          docker build -t ${IMAGE_REPO}:${TAG} ./app
          docker push ${IMAGE_REPO}:${TAG}

      - name: Install yq
        run: |
          curl -L https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
          yq --version

      - name: Update values-dev.yaml (image repo + tag)
        run: |
          TAG=${{ steps.vars.outputs.SHORT_SHA }}
          yq -i ".image.repository = \"${IMAGE_REPO}\"" "${VALUES_FILE}"
          yq -i ".image.tag        = \"${TAG}\""        "${VALUES_FILE}"
          echo "Updated ${VALUES_FILE}:"
          cat "${VALUES_FILE}"

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${{ env.VALUES_FILE }}"
          git commit -m "ci: image -> ${IMAGE_REPO}:${{ steps.vars.outputs.SHORT_SHA }}" || echo "No changes to commit"
          git push